# Generated by Django 4.1.7 on 2023-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_remove_film_genre_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, to='films.genre'),
        ),
    ]
