# Generated by Django 4.1.7 on 2023-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_film_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(blank=True, to='films.country'),
        ),
    ]
