# Generated by Django 4.1.7 on 2023-03-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_basket_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(blank=True, default='Unknown', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(blank=True, default='Unknown', max_length=100, verbose_name='Жанр'),
        ),
    ]
