# Generated by Django 4.1.7 on 2023-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_alter_film_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='countries', to='films.country', verbose_name='Страна'),
        ),
    ]
