# Generated by Django 4.1.7 on 2023-05-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_country_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='country_films', to='films.country', verbose_name='Страна'),
        ),
    ]
