# Generated by Django 4.1.7 on 2023-05-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_alter_film_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(blank=True, to='films.country', verbose_name='Страна'),
        ),
    ]
